using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArmadaReports.Common.Models
{
    [Serializable]
    public class Details
    {
        public string AspnRxId_4_ { get; set; }//1
        public string DoctorFlag_70_ { get; set; }//2
        public string ReferralCode_55_ { get; set; }//3
        public string DoctorId { get; set; }//4
        public string ProgramId { get; set; }//5
        public string PrescriptionId { get; set; }//6
        public string PhysicianFirstName_42_43_ { get; set; } // right 7
        public string PhysicianLastName_42_44_ { get; set; } // right 8
        public string Address1_1__47_ { get; set; } // right 9
        public string Address2_1_47_ { get; set; } // right 10
        public string City_48_ { get; set; }//11
        public string State_50_ { get; set; }//12
        public string PostalCode_51_ { get; set; }//13
        public string Phone { get; set; }//14
        public string Npi_34_45_ { get; set; }//15
        public string PharmacyNpi_41_ { get; set; }//16
        public string LastFillDate__ { get; set; }//17
        public string InsuranceType_31_ { get; set; }//18
        public string InsuranceTypeId { get; set; }//19
        public string InsuranceName_38_87_88_ { get; set; }//20
        public string BinNumber_7_ { get; set; }//21
        public string PcnNumber { get; set; }//22
        public string ReferralDate { get; set; }//23
        public string PrescriptionShipDate { get; set; }//24
        public string DrugName_115_ { get; set; }//25
        public string Strength_76_ { get; set; }//26
        public string Refills_58_ { get; set; }//27
        public string DaysSupply_17_ { get; set; }//28
        public string RegranexTubesFilled_68_ { get; set; }//29
        public string FillQty_21_ { get; set; }//30
        public string OrderQty_35_ { get; set; }//31
        public string FillingPharmacyName_22_ { get; set; }//32
        public string HasNoMemberName { get; set; }//33
        public string ReferringPharmacyContact { get; set; }//34
        public string ReferralPharmacyEmail { get; set; }//35
        public string PrescriptionNumber { get; set; }//36
        public string AspnStatus_63_ { get; set; }//37
        public string ProgramStatus_53_ { get; set; }//38
        public string ProgramSubStatus_65_ { get; set; }//39
        public string ReferralType_69_ { get; set; }//40
        public string HubPatientId_27_ { get; set; }//41
        public string HubNumber_8_ { get; set; }//42
        public string FinalCopay_24_127_ { get; set; }//43
        public string Copay_10_126_ { get; set; }//44
        public string CopayType { get; set; }//45
        public string CptCode { get; set; }//46
        public string CptCopayType { get; set; }//47
        public string CopayCardOffered { get; set; }//48
        public string CopayCardUsed { get; set; }//49
        public string CopayInsPctg { get; set; }//50
        public string CptCopayAmount { get; set; }//51
        public string CptCopayInsPctg { get; set; }//52
        public string PriorAuthRequired_36_ { get; set; }//53
        public string PatientCity { get; set; }//54
        public string PatientState_62_ { get; set; }//55
        public string PatientId_37_ { get; set; }//56
        public string PatientZip { get; set; }//57
        public string Pcn_39_ { get; set; }//58
        public string GroupId_25_ { get; set; }//59
        public string CreatedDate_16_ { get; set; }//60
        public string ReceiveDate { get; set; }//61
        public string ModifyDate { get; set; }//62
        public string AssignDate_5_ { get; set; }//63
        public string AcceptDate { get; set; }//64
        public string CompleteDate { get; set; }//65
        public string CancelDate { get; set; }//66
        public string ShipDate_61_ { get; set; }//67
        public string FillDate_20_ { get; set; }//68
        public string CreatedUserName { get; set; }//69
        public string ModifyUserName { get; set; }//70
        public string AssignUserName { get; set; }//71
        public string AcceptUserName { get; set; }//72
        public string CompleteUserName { get; set; }//73
        public string CancelUserName { get; set; }//74
        public string ProgramName_52_ { get; set; }//75
        public string DaysToFill_19_ { get; set; }//76
        public string ReferrerName_60_ { get; set; }//77
        public string ReportsToName_59_ { get; set; }//78
        public string StepTherapy_64_ { get; set; }//79
        public string TrialCard_67_46_ { get; set; }//80
        public string Indicator_66_ { get; set; }//81
        public string Icd10Code_28_ { get; set; }//82
        public string Icd10LongDesc_29_ { get; set; }//83
        public string Nabp_23_ { get; set; }//84
        public string PdrpFlag_40_ { get; set; } // right 85
        public string NDC_33_ { get; set; }//86
        public string InNetwork_30_ { get; set; }//87
        public string CopayCardActivation_11_ { get; set; }//88
        public string CopayCardNumber_14_ { get; set; }//89
        public string CopayCardGroupId_13_ { get; set; }//90
        public string CopayCardBin_12_ { get; set; }//91
        public string CopayCardPcn_15_ { get; set; }//92
        public string ReceivedOnDate_54_ { get; set; }//93
        public string Specialty_49_ { get; set; }//94
        public string RefillCalcDate_57_ { get; set; }//95
        public string RefillCount_56_ { get; set; }//96
        public string RxAutoFill_6_ { get; set; }//97
        public string Category { get; set; }//98
        public string AuthCode_32_ { get; set; }//99
        public string ProdForm { get; set; }//100
        public string ShipQty { get; set; }//101
        public string DispenseDate { get; set; }//102
        public string NcpDp_82_ { get; set; }//103
        public string PharmacyAddress1 { get; set; }//104
        public string PharmacyCity { get; set; }//105
        public string PharmacyState { get; set; }//106
        public string PharmacyZip { get; set; }//107
        public string TriageLite_74_ { get; set; }//108
        public string Source_75_ { get; set; }//109
        public string RxNumber_77_ { get; set; }//110
        public string MrnNumber_78_ { get; set; }//111
        public string PrimaryMedicalInsurance_79_ { get; set; }//112
        public string SecondaryMedicalInsurance_84_ { get; set; }//113
        public string RegistryPatient_85_ { get; set; }//114
        public string OnLabel_86_ { get; set; }//115
        public string HomeHealthAgency_80_ { get; set; }//116
        public string DistrictManager_81_ { get; set; }//117
        public string AfrezzaASPNID_83_ { get; set; }//118
        public string MedicalInsurancePlan_89_ { get; set; }//119
        public string CoverageType_90_ { get; set; }//120
        public string DaysToProcess_91_ { get; set; }//121
        public string Category_92_ { get; set; }//122
        public string Subcategory_93_ { get; set; }//123
        public string TimetoFill_94_ { get; set; }//124
        public string TimetoShip_95_ { get; set; }//125
        public string IndicationClass_96_ { get; set; }//126
        public string OriginalAspnId_97_ { get; set; }//127
        public string GprSite_98_ { get; set; }//128
        public string BridgeProgram_99_ { get; set; }//129
        public string ExternalPatientID_100_ { get; set; }//130
        public string PAAppealRequired_101_ { get; set; }//131
        public string VoucherFlag_102_ { get; set; }//132
        public string RefillNumber_103_ { get; set; }//133
        public string BenefitTypeUsed_104_ { get; set; }//134
        public string PharmacyInsurancePlan { get; set; }//135
        public string CreatedDatePopup { get; set; }//136
        public string ReceiveDatePopup { get; set; }//137
        public string ModifyDatePopup { get; set; }//138
        public string AssignDatePopup { get; set; }//139
        public string AcceptDatePopup { get; set; }//140
        public string CompleteDatePopup { get; set; }//141
        public string CancelDatePopup { get; set; }//142
        public string ShipDatePopup { get; set; }//143
        public string FillDatePopup { get; set; }//144
        public string LastFillDatePopup { get; set; }//145
        public string ReferralDatePopup { get; set; }//146
        public string PrescriptionShipDatePopup { get; set; }//147
        public string ReceivedOnDatePopup { get; set; }//148
        public string RefillCalcDatePopup { get; set; }//149
        public string DispenseDatePopup { get; set; }//150
        public string ReportToId { get; set; }//151
        public string SalesReferralId { get; set; }//152
        public string PatientConsentName_105_ { get; set; }//153
        public string PatientConsentDOB_106_ { get; set; }//154
        public string CurrentStatusDate_107_ { get; set; }//155
        public string BVOutcome_108_ { get; set; }//156
        public string ReferringPharmacyName_109_ { get; set; }//157
        public string PatientConsent_110_ { get; set; }//158
        public string PatientServicesOptin_111_ { get; set; }//159
        public string PatientTrainingOptin_112_ { get; set; }//160
        public string VoucherId_114_ { get; set; }//161
        public string CaseManager_116_ { get; set; }//162
        public string SubHubCaseManager_117_ { get; set; }//163
        public string SecondaryPharmacyInsurancePlan_118_ { get; set; }//164
        public string AssignmentReason_119_ { get; set; }//165
        public string AssignedUser_120_ { get; set; }//166
        public DateTime CreatedOn { get; set; }//167
        public string PlateletCount_121_ { get; set; }//168
        public string ProcedureDate_122_ { get; set; }//169
        public string FirstDosingDate_123_ { get; set; }//170
        public string PAType_124_ { get; set; }//171
        public string DeliverTo_125_ { get; set; }//172
        public string AspnrRxInternalId { get; set; }
        public string PAStatus_129_ { get; set; }
        public string PriorAuthorizationType_130_ { get; set; }
        public string BenefitInsuranceType_131_ { get; set; }
        public string BenefitInsuranceName_132_ { get; set; }
        public string PhoneNumber_133_ { get; set; }
        public string GroupNumber_134_ { get; set; }
        public string DeductibleAmount_135_ { get; set; }
        public string TotalDeductibleMet_136_ { get; set; }
        public string CanOfficeBuyBill_137_ { get; set; }
        public string PreferredSPP_138_ { get; set; }
        public string DiagnosisCode_139_ { get; set; }
        public string CodeBasedOnMedNecessity_140_ { get; set; }
        public string DoctorInNetwork_141_ { get; set; }
        public string EffectiveDateOnPlan_142_ { get; set; }
        public string OOPMaxAmount_143_ { get; set; }
        public string OOPMetToDate_144_ { get; set; }
        public string HCPCSCodeFields_145_ { get; set; }
        public string Coinsurance_146_ { get; set; }
        public string CoinsuranceType_147_ { get; set; }
        public string PARequired_148_ { get; set; }
        public string PAReqType_149_ { get; set; }
        public string TerritoryName_150_ { get; set; }
        public string HospitalDischarge_151_ { get; set; }
        public string SbsShortBowelSyndrom_152_ { get; set; }
        public string Internalid_153_ { get; set; }
        public string Placeholder_154_ { get; set; }
    }
}
