//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmadaReports.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AnalyticsEntities : DbContext
    {
        public AnalyticsEntities()
            : base("name=AnalyticsEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 500;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetPharmacyById_Result> GetPharmacyById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPharmacyById_Result>("GetPharmacyById", idParameter);
        }
    
        public virtual ObjectResult<GetPrograms_Result> GetPrograms(Nullable<System.Guid> userID, Nullable<System.Guid> applicationID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            var applicationIDParameter = applicationID.HasValue ?
                new ObjectParameter("ApplicationID", applicationID) :
                new ObjectParameter("ApplicationID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrograms_Result>("GetPrograms", userIDParameter, applicationIDParameter);
        }
    
        public virtual ObjectResult<GetScorecardMonthOverMonth_Result> GetScorecardMonthOverMonth(Nullable<System.Guid> userID, Nullable<int> programID, Nullable<long> pharmacyID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            var programIDParameter = programID.HasValue ?
                new ObjectParameter("ProgramID", programID) :
                new ObjectParameter("ProgramID", typeof(int));
    
            var pharmacyIDParameter = pharmacyID.HasValue ?
                new ObjectParameter("PharmacyID", pharmacyID) :
                new ObjectParameter("PharmacyID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScorecardMonthOverMonth_Result>("GetScorecardMonthOverMonth", userIDParameter, programIDParameter, pharmacyIDParameter);
        }
    
        public virtual ObjectResult<GetScorecardPeriod_Result> GetScorecardPeriod(Nullable<System.Guid> userID, Nullable<int> programID, Nullable<long> pharmacyID, string period)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            var programIDParameter = programID.HasValue ?
                new ObjectParameter("ProgramID", programID) :
                new ObjectParameter("ProgramID", typeof(int));
    
            var pharmacyIDParameter = pharmacyID.HasValue ?
                new ObjectParameter("PharmacyID", pharmacyID) :
                new ObjectParameter("PharmacyID", typeof(long));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScorecardPeriod_Result>("GetScorecardPeriod", userIDParameter, programIDParameter, pharmacyIDParameter, periodParameter);
        }
    
        public virtual ObjectResult<GetScorecardPeriodLabels_Result> GetScorecardPeriodLabels(string reportPeriod)
        {
            var reportPeriodParameter = reportPeriod != null ?
                new ObjectParameter("reportPeriod", reportPeriod) :
                new ObjectParameter("reportPeriod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScorecardPeriodLabels_Result>("GetScorecardPeriodLabels", reportPeriodParameter);
        }
    
        public virtual ObjectResult<GetScorecardReferralVolumeVsTimeToFill_Result> GetScorecardReferralVolumeVsTimeToFill(Nullable<System.Guid> userID, Nullable<int> programID, Nullable<long> pharmacyID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            var programIDParameter = programID.HasValue ?
                new ObjectParameter("ProgramID", programID) :
                new ObjectParameter("ProgramID", typeof(int));
    
            var pharmacyIDParameter = pharmacyID.HasValue ?
                new ObjectParameter("PharmacyID", pharmacyID) :
                new ObjectParameter("PharmacyID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScorecardReferralVolumeVsTimeToFill_Result>("GetScorecardReferralVolumeVsTimeToFill", userIDParameter, programIDParameter, pharmacyIDParameter);
        }
    }
}
