//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSellerDataParser.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardinalSPD
    {
        public int Id { get; set; }
        public string FILLER1 { get; set; }
        public string CHG_AMOUNT { get; set; }
        public string CHG_DATE { get; set; }
        public string CHG_NUM { get; set; }
        public string FILLER2 { get; set; }
        public Nullable<double> COST_TOT { get; set; }
        public string FAC_ACCT { get; set; }
        public string FAC_CITY { get; set; }
        public string FAC_DEA { get; set; }
        public string FAC_HIN { get; set; }
        public string FAC_NAME { get; set; }
        public string FILLER3 { get; set; }
        public string PO_NUMBER { get; set; }
        public string FAC_STATE { get; set; }
        public string FILLER4 { get; set; }
        public string FILLER5 { get; set; }
        public string DROP_SHIP { get; set; }
        public string GPO { get; set; }
        public string INV_DATE { get; set; }
        public string INVOICE { get; set; }
        public string NDC { get; set; }
        public string FILLER6 { get; set; }
        public string ORDER_DATE { get; set; }
        public string FILLER7 { get; set; }
        public string PROD_FORM { get; set; }
        public string FILLER8 { get; set; }
        public string PROD_STRNG { get; set; }
        public string FILLER9 { get; set; }
        public string FILLER10 { get; set; }
        public Nullable<int> SHIP_QTY { get; set; }
        public string FILLER11 { get; set; }
        public string FILLER12 { get; set; }
        public string SHIP_DATE { get; set; }
        public Nullable<double> TOT_COST { get; set; }
        public string FILLER13 { get; set; }
        public string PROD_NAME { get; set; }
        public string FILLER14 { get; set; }
        public string FILLER15 { get; set; }
        public string FILLER16 { get; set; }
        public string VENDOR { get; set; }
        public string FILLER17 { get; set; }
        public string FILLER18 { get; set; }
        public string FILLER19 { get; set; }
        public string FILLQR20 { get; set; }
        public string FILLER21 { get; set; }
        public string FILLER22 { get; set; }
        public string FILLAR23 { get; set; }
        public Nullable<System.DateTime> BATCH { get; set; }
        public Nullable<double> COST { get; set; }
        public Nullable<int> WHID { get; set; }
        public Nullable<int> WRPID { get; set; }
        public string WHOLESALER { get; set; }
        public string DC_NAME { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
        public string WH_CONT { get; set; }
        public Nullable<int> MATCH_COID { get; set; }
        public string MATCH_TYPE { get; set; }
        public string SALE_CR { get; set; }
        public Nullable<int> MMID { get; set; }
        public Nullable<int> ITID { get; set; }
        public string SALE_CRW { get; set; }
        public string SALE_CRSRC { get; set; }
        public string EXTRA { get; set; }
    }
}
