//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSellerDataParser.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardinal
    {
        public int Id { get; set; }
        public string DC_NAME { get; set; }
        public string DC_NR { get; set; }
        public string FAC_ACCT { get; set; }
        public string DC_DEA { get; set; }
        public string FAC_DEA { get; set; }
        public string FAC_NAME { get; set; }
        public string WH_OEN { get; set; }
        public string NDC { get; set; }
        public string NDC13 { get; set; }
        public string VENDOR { get; set; }
        public string PROD_NAME { get; set; }
        public string GENERIC { get; set; }
        public string PROD_UD { get; set; }
        public string PROD_FORM { get; set; }
        public string PROD_STRNG { get; set; }
        public Nullable<int> ITEM_SIZE { get; set; }
        public string FILLER4 { get; set; }
        public string INVOICE { get; set; }
        public Nullable<double> PROD_SIZE { get; set; }
        public string FILLER5 { get; set; }
        public string IDATE { get; set; }
        public string COST_PLLUS { get; set; }
        public string WAC { get; set; }
        public string AWP { get; set; }
        public Nullable<int> AHFS { get; set; }
        public string GPO { get; set; }
        public string SDATE { get; set; }
        public Nullable<int> SHIP_QTY { get; set; }
        public string COST { get; set; }
        public string CONTRACT { get; set; }
        public Nullable<System.DateTime> BATCH { get; set; }
        public string WHOLESALER { get; set; }
        public string SALE_CR { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
        public Nullable<int> MMID { get; set; }
        public Nullable<int> ITID { get; set; }
        public Nullable<int> WHID { get; set; }
        public Nullable<int> WRPID { get; set; }
        public Nullable<int> MATCH_COID { get; set; }
        public string MATCH_TYPE { get; set; }
        public string WH_CONT { get; set; }
        public string SALE_CRW { get; set; }
        public string SALE_CRSRC { get; set; }
        public string EXTRA { get; set; }
    }
}
