//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholeSellerDataParser.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuraScript
    {
        public int Id { get; set; }
        public string FAC_ACCT { get; set; }
        public string FAC_NAME { get; set; }
        public string FILLER1 { get; set; }
        public string FILLER2 { get; set; }
        public string FAC_CITY { get; set; }
        public string FAC_STATE { get; set; }
        public string FAC_ZIP { get; set; }
        public string FAC_DEA { get; set; }
        public string CONTRACT { get; set; }
        public string VENDOR { get; set; }
        public string PROD_NAME { get; set; }
        public string VE_ITEMNR { get; set; }
        public string LOT_NUMBER { get; set; }
        public string LOT_EXPR { get; set; }
        public string NDC { get; set; }
        public string WH_OEN { get; set; }
        public string INV_DATE { get; set; }
        public string INVOICE { get; set; }
        public string FILLER3 { get; set; }
        public Nullable<int> SHIP_QTY { get; set; }
        public Nullable<double> COST { get; set; }
        public Nullable<double> TOT_COST { get; set; }
        public Nullable<double> TOT_FEE { get; set; }
        public Nullable<System.DateTime> BATCH { get; set; }
        public string WH_CONT { get; set; }
        public string WHOLESALER { get; set; }
        public Nullable<int> MATCH_COID { get; set; }
        public string MATCH_TYPE { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
        public Nullable<int> MMID { get; set; }
        public Nullable<int> ITID { get; set; }
        public Nullable<int> WHID { get; set; }
        public Nullable<int> WRPID { get; set; }
        public string SALE_CR { get; set; }
        public string SALE_CRW { get; set; }
        public string SALE_CRSRC { get; set; }
        public string EXTRA { get; set; }
    }
}
