//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class MCKESSON
{
    public int Id { get; set; }
    public string WHOLESALER { get; set; }
    public string FAC_ACCT { get; set; }
    public string FAC_NAME { get; set; }
    public string FAC_ADDR { get; set; }
    public string FAC_CITY { get; set; }
    public string FAC_STATE { get; set; }
    public string FAC_ZIP { get; set; }
    public string FAC_DEA { get; set; }
    public string SHIP_DATE { get; set; }
    public string INV_DATE { get; set; }
    public string INVOICE { get; set; }
    public string PO_NUMBER { get; set; }
    public string VENDOR { get; set; }
    public string VE_ACCT { get; set; }
    public string VE_ITEMNR { get; set; }
    public string PROD_NAME { get; set; }
    public string DC_NR { get; set; }
    public string NDC { get; set; }
    public string UPC { get; set; }
    public string FILLER01 { get; set; }
    public string FILLER02 { get; set; }
    public string FILLER03 { get; set; }
    public string FILLER04 { get; set; }
    public string PROD_FORM { get; set; }
    public string GEN_ID { get; set; }
    public string GEN_NAME { get; set; }
    public string PROD_STRNG { get; set; }
    public string PROD_SIZE { get; set; }
    public string GEN_IND { get; set; }
    public string PROD_UM { get; set; }
    public string FILLER05 { get; set; }
    public Nullable<double> AWP { get; set; }
    public Nullable<double> WAC { get; set; }
    public Nullable<int> ORDER_QTY { get; set; }
    public Nullable<int> SHIP_QTY { get; set; }
    public Nullable<double> COST { get; set; }
    public Nullable<double> TOT_COST { get; set; }
    public Nullable<int> NEWEXTRA { get; set; }
    public string GPO { get; set; }
    public string CONTRACT { get; set; }
    public string LEAD_NAME { get; set; }
    public string REASON_NS { get; set; }
    public string WH_NOTES { get; set; }
    public string CREDIT_CD { get; set; }
    public string REASON_DES { get; set; }
    public Nullable<double> CHG_AMOUNT { get; set; }
    public string FILLER06 { get; set; }
    public string FILLER07 { get; set; }
    public Nullable<System.DateTime> BATCH { get; set; }
    public string SALE_CR { get; set; }
    public Nullable<int> MMID { get; set; }
    public Nullable<int> ITID { get; set; }
    public Nullable<int> WRPID { get; set; }
    public string DC_NAME { get; set; }
    public string WH_CONT { get; set; }
    public Nullable<int> MATCH_COID { get; set; }
    public string MATCH_TYPE { get; set; }
    public Nullable<System.DateTime> REC_DATE { get; set; }
    public string SALE_CRW { get; set; }
    public string SALE_CRSRC { get; set; }
    public string EXTRA { get; set; }
}
