//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class MorrisDickson
{
    public int Id { get; set; }
    public string FCDATE { get; set; }
    public string DC_NAME { get; set; }
    public string DC_DEA { get; set; }
    public string FAC_NAME { get; set; }
    public string FAC_DEA { get; set; }
    public string FAC_HIN { get; set; }
    public string FAC_CITY { get; set; }
    public string FAC_STATE { get; set; }
    public string CWAC { get; set; }
    public string CCOST { get; set; }
    public string CQTY { get; set; }
    public string SALE_CR { get; set; }
    public string CONTRACT { get; set; }
    public string CONT_START { get; set; }
    public string NDC { get; set; }
    public string OLD_NDC { get; set; }
    public string UPC { get; set; }
    public string UPN { get; set; }
    public string FILLER { get; set; }
    public string INVOICE { get; set; }
    public string SDATE { get; set; }
    public string CTOTAL { get; set; }
    public string PROD_NAME { get; set; }
    public string PROD_SIZE { get; set; }
    public string PROD_STRNG { get; set; }
    public string DC_NR { get; set; }
    public string FAC_ACCT { get; set; }
    public string WH_OEN { get; set; }
    public string VE_ITEMNR { get; set; }
    public string FILLER1 { get; set; }
    public string VENDOR { get; set; }
    public string IDATE { get; set; }
    public string CHG_NUM { get; set; }
    public string CONVERSION { get; set; }
    public string CREDREBILL { get; set; }
    public string DISCOUNT { get; set; }
    public string BATCH { get; set; }
    public string WHOLESALER { get; set; }
    public string WH_CONT { get; set; }
    public Nullable<int> MATCH_COID { get; set; }
    public string MATCH_TYPE { get; set; }
    public Nullable<int> SHIP_QTY { get; set; }
    public Nullable<decimal> COST { get; set; }
    public Nullable<decimal> TOT_COST { get; set; }
    public Nullable<decimal> WAC { get; set; }
    public Nullable<System.DateTime> SHIP_DATE { get; set; }
    public Nullable<System.DateTime> INV_DATE { get; set; }
    public Nullable<System.DateTime> REC_DATE { get; set; }
    public Nullable<int> MMID { get; set; }
    public Nullable<int> WHID { get; set; }
    public Nullable<int> WRPID { get; set; }
    public Nullable<int> ITID { get; set; }
    public string SALE_CRW { get; set; }
    public string SALE_CRSRC { get; set; }
    public string EXTRA { get; set; }
}
