//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ValleyWholesale
{
    public int Id { get; set; }
    public string PDATE { get; set; }
    public string WHOLESALER { get; set; }
    public string DC_DEA { get; set; }
    public string FAC_NAME { get; set; }
    public string FAC_DEA { get; set; }
    public string CWAC { get; set; }
    public string CCOST { get; set; }
    public string CQTY { get; set; }
    public string SALE_CR { get; set; }
    public string CONTRACT { get; set; }
    public string PROD_CODE { get; set; }
    public string NDC { get; set; }
    public string INVOICE { get; set; }
    public string SDATE { get; set; }
    public string CTOT_COST { get; set; }
    public string PROD_NAME { get; set; }
    public string DI { get; set; }
    public string UP_CHARGE { get; set; }
    public string DIVISION { get; set; }
    public string FAC_ACCT { get; set; }
    public string VE_ITEMNR { get; set; }
    public string IDATE { get; set; }
    public string VENDOR { get; set; }
    public string BATCH { get; set; }
    public Nullable<decimal> WAC { get; set; }
    public Nullable<decimal> COST { get; set; }
    public Nullable<int> SHIP_QTY { get; set; }
    public Nullable<decimal> TOT_COST { get; set; }
    public string MATCH_TYPE { get; set; }
    public Nullable<System.DateTime> SHIP_DATE { get; set; }
    public Nullable<System.DateTime> INV_DATE { get; set; }
    public string WH_CONT { get; set; }
    public Nullable<int> MATCH_COID { get; set; }
    public Nullable<System.DateTime> REC_DATE { get; set; }
    public Nullable<int> MMID { get; set; }
    public Nullable<int> WHID { get; set; }
    public Nullable<int> WRPID { get; set; }
    public Nullable<int> ITID { get; set; }
    public string SALE_CRW { get; set; }
    public string SALE_CRSRC { get; set; }
    public string EXTRA { get; set; }
}
