//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ValueDrug
{
    public int Id { get; set; }
    public string DcName { get; set; }
    public string DcDea { get; set; }
    public string WholeSaler { get; set; }
    public string FacName { get; set; }
    public string FacDea { get; set; }
    public string FacHin { get; set; }
    public string FacCity { get; set; }
    public string FacState { get; set; }
    public string FacAcct { get; set; }
    public string COrderDate { get; set; }
    public string CShipDate { get; set; }
    public string CInvDate { get; set; }
    public string Invoice { get; set; }
    public string Vendor { get; set; }
    public string WhOEN { get; set; }
    public string NDC { get; set; }
    public string UPC { get; set; }
    public string VeItemNR { get; set; }
    public string ProdName { get; set; }
    public string ProdForm { get; set; }
    public string ProdStrng { get; set; }
    public string ProdSize { get; set; }
    public string ProdUM { get; set; }
    public string ProdUD { get; set; }
    public string OuterPK { get; set; }
    public string Cwac { get; set; }
    public string COrderQty { get; set; }
    public string CShipQty { get; set; }
    public string CCost { get; set; }
    public string CUPDNCHG { get; set; }
    public string CTotCost { get; set; }
    public string Contract { get; set; }
    public string GPO { get; set; }
    public string CCHGDate { get; set; }
    public string CHGNum { get; set; }
    public string CCHGAmount { get; set; }
    public string CapRDate { get; set; }
    public string PrivContr { get; set; }
    public string Special { get; set; }
    public string NetItem { get; set; }
    public string ReasonNS { get; set; }
    public string DropShip { get; set; }
    public string PONumber { get; set; }
    public string WhNotes { get; set; }
    public string Batch { get; set; }
    public Nullable<System.DateTime> OderDate { get; set; }
    public Nullable<System.DateTime> ShipDate { get; set; }
    public Nullable<System.DateTime> InvDate { get; set; }
    public string WAC { get; set; }
    public Nullable<int> OrderQty { get; set; }
    public Nullable<int> ShipQty { get; set; }
    public string Cost { get; set; }
    public string UpDnCHG { get; set; }
    public string TotCost { get; set; }
    public Nullable<System.DateTime> ChgDate { get; set; }
    public string ChgAmount { get; set; }
    public Nullable<System.DateTime> ApprDate { get; set; }
    public string WhCont { get; set; }
    public Nullable<int> MatchCoid { get; set; }
    public string MatchType { get; set; }
    public Nullable<int> MMId { get; set; }
    public Nullable<int> ITId { get; set; }
    public Nullable<int> WHId { get; set; }
    public Nullable<int> WRPId { get; set; }
    public string SaleCR { get; set; }
    public Nullable<System.DateTime> RecDate { get; set; }
    public string SaleCRW { get; set; }
    public string SaleCRSRC { get; set; }
    public string Extra { get; set; }
}
